name: f_agenda_de_contatos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: ^1.3.0 # SQLite plugin for flutter
  url_launcher: ^5.4.2 # plugin for launching a URL in the mobile platform (Irá abrir o telefone)
  image_picker: ^0.6.4 # plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/person.png
